### ISSUE TITLE
Logo Image Copyright

### ISSUE THREAD

**Issue by NovaFox161** [dotimothy/gratition#1]
Hey, I'm just wanting to let you know that I was made aware you are currently using one of my project's logos for this project.

The image belongs to my Discord bot, DisCal which can be seen:
- [On our website](https://discalbot.com/)
- [GitHub](https://github.com/DreamExposure/DisCal-Discord-Bot)
- [And the original file sources](https://github.com/DreamExposure/DisCal-Discord-Bot/tree/master/web/src/main/resources/static/assets/img/logos)

I see that you are using the image here: [images/logo.png](https://github.com/dotimothy/gratition/blob/main/images/logo.png)

I have no doubt your intentions are good, but I'd like to ask if you could change your project's logo away from ours.

Thank you

**Comment by ghost** [comment]
Will do soon. Thank you for letting us know.

**Comment by dotimothy** [comment]
Hi NovaFox,

We updated the website logo so it wouldn't use your logo anymore. We will close the issue, and again, apologies for us unknowingly using your logo.

Let us know if you have any other issues!

Regards,
Timothy

**Comment by NovaFox161** [comment]
Thanks so much! Not a problem at all
